name: cse_kch
description: "CSE KCH – app desktop (macOS/Windows) avec Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & utilitaires
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5
  window_size: ^0.1.0
  collection: ^1.19.1
  uuid: ^4.5.1

  # Plateforme / fichiers / permissions
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^10.1.9
  open_filex: ^4.7.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  device_info_plus: ^12.1.0
  url_launcher: ^6.3.1
  http: ^1.5.0

  # PDF / partage
  pdf: ^3.11.3
  share_plus: ^12.0.0

  # Divers
  barcode: ^2.2.9
  crypto: ^3.0.6
  base45: ^0.0.3

  # Firebase
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: assets/icon/icon.png   # ton fichier
  macos:
    generate: true
    image_path: assets/icon/cse.png
  windows:
    generate: true
    image_path: assets/icon/cse.png
    icon_size: 256              

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Inter-Regular.ttf
    - assets/fonts/Inter-Bold.ttf
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Italic.ttf
    - assets/fonts/Roboto-BoldItalic.ttf

