// lib/tools/seed_vehicules.dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

Future<void> seedVehiculesAdminAligned() async {
  final db = FirebaseFirestore.instance;
  var batch = db.batch();

  const source = [
    {
      "immatriculation": "FK-937-JJ",
      "date_entree": "09/12/2019",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Sud",
      "collaborateur": "Fabrice Geoffroy",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EZ-061-VJ",
      "date_entree": "18/09/2018",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Sud",
      "collaborateur": "Stéphane ADALA",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EK-080-YB",
      "date_entree": "23/03/2017",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Sud",
      "collaborateur": "Réserve KPVB",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EL-261-FG",
      "date_entree": "04/05/2017",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Sud",
      "collaborateur": "Réserve KVYVS",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EL-305-FG",
      "date_entree": "12/04/2017",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Sud",
      "collaborateur": "Médiation",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EL-463-FG",
      "date_entree": "15/05/2017",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Sud",
      "collaborateur": "Fatima",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-380-BH",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Sud",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-180-BJ",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Sud",
      "collaborateur": "Médiation",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EQ-476-BV",
      "date_entree": "19/10/2017",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Sud",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GL-526-DK",
      "date_entree": "02/01/2023",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Sud",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GL-614-DK",
      "date_entree": "02/01/2023",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Sud",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GL-461-DK",
      "date_entree": "30/12/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Sud",
      "collaborateur": "Médiation",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GL-574-DK",
      "date_entree": "30/12/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Sud",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GL-265-LE",
      "date_entree": "06/02/2023",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Sud",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "FC-314-EY",
      "date_entree": "17/01/2019",
      "marque": "Renault",
      "modele": "Kangoo",
      "base_geographique": "Sud",
      "collaborateur": "Médiation",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GF-578-VP",
      "date_entree": "11/05/2022",
      "marque": "Citroën",
      "modele": "C3",
      "base_geographique": "Sud",
      "collaborateur": "Eric METREAU",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "FK-970-JJ",
      "date_entree": "16/12/2019",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Ouest",
      "collaborateur": "BERROUKECHE Driss",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EQ-654-BV",
      "date_entree": "19/10/2017",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Ouest",
      "collaborateur": "BAMBA Cédric",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-023-BH",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Ouest",
      "collaborateur": "Médiation",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-971-BG",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Ouest",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-989-BG",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Ouest",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EZ-155-VJ",
      "date_entree": "18/09/2018",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Ouest",
      "collaborateur": "BELHIMER Mourad",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-949-BG",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Ouest",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-979-BH",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Ouest",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EL-145-FG",
      "date_entree": "15/05/2017",
      "marque": "Renault",
      "modele": "Clio Estate",
      "base_geographique": "Ouest",
      "collaborateur": "Médiation",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-004-BH",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Ouest",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-075-BJ",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Ouest",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GK-771-BH",
      "date_entree": "02/11/2022",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Ouest",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GB-813-WK",
      "date_entree": "27/09/2021",
      "marque": "Citroën",
      "modele": "Spacetourer",
      "base_geographique": "Ouest",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GE-279-EM",
      "date_entree": "01/02/2022",
      "marque": "Citroën",
      "modele": "C3",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "FF-849-MK",
      "date_entree": "26/06/2019",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "DJ-147-LV",
      "date_entree": "19/08/2024",
      "marque": "Renault",
      "modele": "Master",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "FD-141-TK",
      "date_entree": "08/03/2019",
      "marque": "Citroën",
      "modele": "C4 Cactus",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EQ-604-BV",
      "date_entree": "01/10/2017",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EL-492-FB",
      "date_entree": "14/05/2017",
      "marque": "Renault",
      "modele": "Clio Estate",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GL-023-LC",
      "date_entree": "17/02/2023",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "HB-752-QW",
      "date_entree": "30/01/2025",
      "marque": "Citroën",
      "modele": "C3",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "HC-529-CD",
      "date_entree": "26/02/2025",
      "marque": "Peugeot",
      "modele": "208 II",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "HD-109-SC",
      "date_entree": "26/05/2025",
      "marque": "Volkswagen",
      "modele": "Polo VI",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "HD-374-JC",
      "date_entree": "02/05/2025",
      "marque": "Dacia",
      "modele": "Sandero III",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "HD-730-WQ",
      "date_entree": "02/06/2025",
      "marque": "Renault",
      "modele": "Clio 4",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GZ-040-LS",
      "date_entree": "01/09/2024",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GZ-148-LS",
      "date_entree": "01/09/2024",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GZ-297-XX",
      "date_entree": "01/10/2024",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GZ-329-XX",
      "date_entree": "28/10/2024",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GZ-367-XX",
      "date_entree": "28/10/2024",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GZ-788-LR",
      "date_entree": "30/09/2024",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GZ-896-LR",
      "date_entree": "01/09/2024",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GZ-975-LR",
      "date_entree": "01/09/2024",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GD-442-WC",
      "date_entree": "13/01/2022",
      "marque": "Citroën",
      "modele": "C3",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "BY-672-KZ",
      "date_entree": "01/12/2011",
      "marque": "Renault",
      "modele": "Master",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EZ-803-VH",
      "date_entree": "18/09/2018",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "HC-246-HF",
      "date_entree": "07/03/2025",
      "marque": "Renault",
      "modele": "Espace VI",
      "base_geographique": "Nord",
      "collaborateur": "DIRECTION",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "EG-978-EM",
      "date_entree": "23/11/2016",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "FE-088-NE",
      "date_entree": "15/07/2019",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "FP-971-QT",
      "date_entree": "29/04/2020",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Ouest",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GB-363-VJ",
      "date_entree": "22/08/2022",
      "marque": "Renault",
      "modele": "Clio",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "GL-416-DK",
      "date_entree": "02/01/2023",
      "marque": "Citroën",
      "modele": "Berlingo",
      "base_geographique": "Sud",
      "collaborateur": "Contrôle",
      "statut": "Actif",
      "prochain_ct": "",
    },
    {
      "immatriculation": "FN-250-YL",
      "date_entree": "24/02/2020",
      "marque": "Renault",
      "modele": "Trafic",
      "base_geographique": "Nord",
      "collaborateur": "",
      "statut": "Actif",
      "prochain_ct": "",
    },
  ];

  int counter = 1;
  int written = 0;

  for (final v in source) {
    final immat = (v['immatriculation'] as String? ?? '').trim();
    if (immat.isEmpty) continue;

    final data = <String, dynamic>{
      'id': counter, // INT attendu par ton modèle
      'immatriculation': immat,
      'date_entree': v['date_entree'] ?? '',
      'marque': v['marque'] ?? '',
      'modele': v['modele'] ?? '',
      'base_geographique': v['base_geographique'] ?? '',
      'collaborateur': v['collaborateur'] ?? '',
      'statut': v['statut'] ?? '',
      'prochain_ct': v['prochain_ct'] ?? '',
      'created_at': FieldValue.serverTimestamp(),
    };

    final ref = db
        .collection('vehicules')
        .doc(counter.toString()); // docId = id
    batch.set(ref, data, SetOptions(merge: true)); // upsert
    counter++;
    written++;

    if (written % 450 == 0) {
      await batch.commit();
      if (kDebugMode) debugPrint('Seed partiel: $written');
      batch = db.batch();
    }
  }

  await batch.commit();
  if (kDebugMode) debugPrint('Seed terminé: $written');
}
