import 'package:cse_kch/models/vehicule.dart';

final List<Vehicule> vehiculeSeed = [
  Vehicule(
    id: null,
    immatriculation: 'BY-672-KZ',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '30-11-2015',
  ),
  Vehicule(
    id: null,
    immatriculation: 'DJ-147-LV',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '18-08-2018',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EG-978-EM',
    dateEntree: '23-11-2016',
    marque: 'Renault',
    modele: 'Trafic',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Inactif',
    prochainCtTech: '30-12-1903',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EK-080-YB',
    dateEntree: '23-03-2017',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '19-03-2021',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EL-145-FG',
    dateEntree: '15-05-2017',
    marque: 'Renault',
    modele: 'Clio Estate',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Inactif',
    prochainCtTech: '30-12-1903',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EL-261-FG',
    dateEntree: '04-05-2017',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-03-2021',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EL-305-FG',
    dateEntree: '12-04-2017',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-03-2021',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EL-463-FG',
    dateEntree: '15-05-2017',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-03-2021',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EL-492-FB',
    dateEntree: '14-05-2017',
    marque: 'Renault',
    modele: 'Clio Estate',
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '28-03-2021',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EQ-476-BV',
    dateEntree: '19-10-2017',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '27-08-2021',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EQ-604-BV',
    dateEntree: '01-10-2017',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '27-08-2021',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EQ-654-BV',
    dateEntree: '19-10-2017',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '27-08-2021',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EZ-061-VJ',
    dateEntree: '18-09-2018',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '19-08-2022',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EZ-155-VJ',
    dateEntree: '18-09-2018',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '19-08-2022',
  ),
  Vehicule(
    id: null,
    immatriculation: 'EZ-803-VH',
    dateEntree: '18-09-2018',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '19-08-2022',
  ),
  Vehicule(
    id: null,
    immatriculation: 'FC-314-EY',
    dateEntree: '17-01-2019',
    marque: 'Renault',
    modele: 'Kangoo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-11-2022',
  ),
  Vehicule(
    id: null,
    immatriculation: 'FD-141-TK',
    dateEntree: '08-03-2019',
    marque: 'Citroën',
    modele: 'C4 Cactus',
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '10-02-2023',
  ),
  Vehicule(
    id: null,
    immatriculation: 'FE-088-NE',
    dateEntree: '15-07-2019',
    marque: 'Renault',
    modele: 'Trafic',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Inactif',
    prochainCtTech: '30-12-1903',
  ),
  Vehicule(
    id: null,
    immatriculation: 'FF-849-MK',
    dateEntree: '26-06-2019',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '16-04-2023',
  ),
  Vehicule(
    id: null,
    immatriculation: 'FK-937-JJ',
    dateEntree: '09-12-2019',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '24-09-2023',
  ),
  Vehicule(
    id: null,
    immatriculation: 'FK-970-JJ',
    dateEntree: '16-12-2019',
    marque: 'Renault',
    modele: 'Clio',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '24-09-2023',
  ),
  Vehicule(
    id: null,
    immatriculation: 'FN-250-YL',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Restitué',
    prochainCtTech: '30-12-1903',
  ),
  Vehicule(
    id: null,
    immatriculation: 'FP-971-QT',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Inactif',
    prochainCtTech: '30-12-1903',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GB-813-WK',
    dateEntree: '27-09-2021',
    marque: 'Citroën',
    modele: 'Spacetourer',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '19-09-2025',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GD-442-WC',
    dateEntree: '13-01-2022',
    marque: 'Citroën',
    modele: 'C3',
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '27-12-2025',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GE-279-EM',
    dateEntree: '01-02-2022',
    marque: 'Citroën',
    modele: 'C3',
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '18-01-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GF-578-VP',
    dateEntree: '11-05-2022',
    marque: 'Citroën',
    modele: 'C3',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '13-04-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-004-BH',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-023-BH',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-075-BJ',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-180-BJ',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-380-BH',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-771-BH',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-949-BG',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-971-BG',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-979-BH',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GK-989-BG',
    dateEntree: '02-11-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'OUEST',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '17-10-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GL-023-LC',
    dateEntree: '17-02-2023',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-12-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GL-265-LE',
    dateEntree: '06-02-2023',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-12-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GL-416-DK',
    dateEntree: '02-01-2023',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '15-12-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GL-461-DK',
    dateEntree: '30-12-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '15-12-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GL-526-DK',
    dateEntree: '02-01-2023',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '15-12-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GL-574-DK',
    dateEntree: '30-12-2022',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '15-12-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GL-614-DK',
    dateEntree: '02-01-2023',
    marque: 'Citroën',
    modele: 'Berlingo',
    baseGeo: 'SUD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '15-12-2026',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GZ-040-LS',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-09-2028',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GZ-148-LS',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-09-2028',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GZ-297-XX',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '27-10-2028',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GZ-329-XX',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '27-10-2028',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GZ-367-XX',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GZ-788-LR',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-09-2028',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GZ-896-LR',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-09-2028',
  ),
  Vehicule(
    id: null,
    immatriculation: 'GZ-975-LR',
    dateEntree: null,
    marque: null,
    modele: null,
    baseGeo: 'NORD',
    collaborateur: null,
    statut: 'Actif',
    prochainCtTech: '29-09-2028',
  ),
];
